shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/portfolio
  - packages/m-league-reviewer
  - packages/dblp
  - packages/react-renderer
  - packages/mortal-ui
  - packages/echarts-dashboard
  - packages/vue-trello
  - packages/vue-design
  - packages/vue-challenges
