/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Advice: typeof import('./src/components/Advice.vue')['default']
    Ankan: typeof import('./src/components/Ankan.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Chi: typeof import('./src/components/Chi.vue')['default']
    Claim: typeof import('./src/components/Claim.vue')['default']
    Daiminkan: typeof import('./src/components/Daiminkan.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    GameInfo: typeof import('./src/components/GameInfo.vue')['default']
    Kakan: typeof import('./src/components/Kakan.vue')['default']
    LoadingSquare: typeof import('./src/components/LoadingSquare.vue')['default']
    Pon: typeof import('./src/components/Pon.vue')['default']
    Score: typeof import('./src/components/Score.vue')['default']
    Tile: typeof import('./src/components/Tile.vue')['default']
    TileGroup: typeof import('./src/components/TileGroup.vue')['default']
  }
}
